//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Service
    {
        public int ServiceId { get; set; }
        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalýdýr.")]
        public string Title { get; set; }


        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(200, ErrorMessage = "En fazla 200 karakter olmalýdýr.")]
        public string Description { get; set; }


        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(100, ErrorMessage = "En fazla 100 karakter olmalýdýr.")]
        public string Icon { get; set; }


        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalýdýr.")]
        public string Experience1 { get; set; }


        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalýdýr.")]
        public string Experience2 { get; set; }


        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalýdýr.")]
        public string Experience3 { get; set; }
    }
}
