//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int Id { get; set; }
        public string ProfileSideBarName { get; set; }
        public string ProfileSideBarTitle { get; set; }
        public string AboutSideBarTitle { get; set; }
        public string EducationSideBarTitle { get; set; }
        public string ExperienceSideBarTitle { get; set; }
        public string SkillSideBarTitle { get; set; }
        public string ServicesSideBarTitle { get; set; }
        public string WorkSideBarTitle { get; set; }
        public string TestimonialSideBarTitle { get; set; }
        public string ContactSideBarTitle { get; set; }
        public string FooterNameSurname { get; set; }
        public string PartialHeadTitle { get; set; }
        public string PartialHeadKeywords { get; set; }
        public string PartialHeadDescription { get; set; }
        public string FooterTitle { get; set; }
    }
}
