//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Settings
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(30, ErrorMessage = "En fazla 30 karakter olmalıdır.")]
        public string ProfileSideBarName { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string ProfileSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan bo� ge�ilemez.")]
        [MaxLength(60, ErrorMessage = "En fazla 60 karakter olmalıdır.")]
        public string AboutSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string EducationSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string ExperienceSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string SkillSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string ServicesSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string WorkSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string TestimonialSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(150, ErrorMessage = "En fazla 150 karakter olmalıdır.")]
        public string ContactSideBarTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string FooterNameSurname { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(150, ErrorMessage = "En fazla 150 karakter olmalıdır.")]
        public string PartialHeadTitle { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(150, ErrorMessage = "En fazla 150 karakter olmalıdır.")]
        public string PartialHeadKeywords { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(500, ErrorMessage = "En fazla 500 karakter olmalıdır.")]
        public string PartialHeadDescription { get; set; }


        [Required(ErrorMessage = "Bu alan boş geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalıdır.")]
        public string FooterTitle { get; set; }
    }
}