//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Testimonial
    {
        public int TestimonialId { get; set; }

        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalýdýr.")]
        public string Title { get; set; }


        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(250, ErrorMessage = "En fazla 250 karakter olmalýdýr.")]
        public string Comment { get; set; }


        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(250, ErrorMessage = "En fazla 250 karakter olmalýdýr.")]
        public string ImageUrl { get; set; }


        [Required(ErrorMessage = "Bu alan boþ geçilemez.")]
        [MaxLength(50, ErrorMessage = "En fazla 50 karakter olmalýdýr.")]
        public string NameSurname { get; set; }
    }
}